import sys
from peer import start_receiver_mode, start_sender_mode, handle_file_sending
from network_utils import receive_msg

def main():
    print("=== P2P RELIABLE FILE TRANSFER SYSTEM ===")
    print("1. Act as Sender")
    print("2. Act as Receiver")
    print("3. Both (Bidirectional Transfer)")
    
    choice = input("Select an option (1-3): ").strip()
    
    if choice == '1':
        # Sender Mode
        code = input("Enter the unique code generated by the receiver: ").strip()
        try:
            sock = start_sender_mode(code)
            handle_file_sending(sock)
            sock.close()
        except Exception as e:
            print(f"Sender Error: {e}")
            
    elif choice == '2':
        # Receiver Mode
        try:
            sock = start_receiver_mode()
            print("Awaiting incoming file transfer...")
            receive_msg(sock)
            sock.close()
        except Exception as e:
            print(f"Receiver Error: {e}")
            
    elif choice == '3':
        # Both Mode (Bidirectional Channel)
        role_setup = input("Who sets up the connection host? (Type 'sender' or 'receiver'): ").strip().lower()
        
        if role_setup == 'receiver':
            try:
                sock = start_receiver_mode()
                # 1. Receive the file from the primary sender first
                print("\nWaiting to receive file from sender...")
                receive_msg(sock)
                
                # 2. Now instantly send a file back without needing a code
                print("\n--- Bidirectional Phase: Now you can send a file back ---")
                send_back = input("Do you want to send a file back to the sender? (y/n): ").strip().lower()
                if send_back == 'y':
                    handle_file_sending(sock)
                sock.close()
            except Exception as e:
                print(f"Error: {e}")
                
        elif role_setup == 'sender':
            code = input("Enter the unique code generated by the partner: ").strip()
            try:
                sock = start_sender_mode(code)
                # 1. Send the initial file
                handle_file_sending(sock)
                
                # 2. Keep socket alive to listen for any file coming back
                print("\nWaiting for potential return file transfer from partner...")
                receive_msg(sock)
                sock.close()
            except Exception as e:
                print(f"Error: {e}")
        else:
            print("Invalid initialization role choice.")
    else:
        print("Invalid menu option selected.")

if __name__ == "__main__":
    main()